Chenge error logic

diff --git a/hpipe b/hpipe
--- a/hpipe
+++ b/hpipe
@@ -23,20 +23,20 @@ done
 
 function main() {
 	log "Start HPipe"
-	CONFIGS="$(conf_load_from_file "$HP_CONFIG_PATH")"
-	PROJECTS="$(conf_get_projects "$CONFIGS")"
+	CONFIGS="$(conf_load_from_file "$HP_CONFIG_PATH")" || { echo "Unable to read file config file"; exit $CONF_ERROR; }
+	PROJECTS="$(conf_get_projects "$CONFIGS")" || { echo "Unable to proess jq config. Query project: $JQ_PATH_PROJECTS"; exit $CONF_ERROR; }
 	pipelines_resolve_all "$PROJECTS"
 	log "End HPipe"
 }
 
 function conf_load_from_file() {
 	FILE_PATH="${1?Missing file path parameter}"
-	jq -c . "$FILE_PATH" || { echo "Unable to read file config file"; exit $CONF_ERROR; }
+	jq -c . "$FILE_PATH"
 }
 
 function conf_get_projects() {
 	CONFIGS="${1?Missing configs parameter}"
-	echo "$CONFIGS" | jq -c "$JQ_PATH_PROJECTS" || { echo "Unable to proess jq config. Query project: $JQ_PATH_PROJECTS"; exit $CONF_ERROR; }
+	echo "$CONFIGS" | jq -c "$JQ_PATH_PROJECTS"
 }
 
 function pipelines_resolve_all() {
